---
title: "HW 4 pt2"
output:
  pdf_document: default
  html_document: default
date: '2023-04-18'
---

# Question 12.22 From Hansen Econometrics

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
options(digits=2)
```

```{r}
# Load packages
pacman::p_load(tidyverse, magrittr, here, haven, magrittr, AER, fixest, cragg, ivmodel, momentfit)

# Load data
ajr_df = read_dta(here("AJR2001/AJR2001.dta"))
```

### Part a)

```{r include=FALSE}
# Estimate 12.86 loggdp = b0 + b1risk
reg1 = ajr_df %>% lm(loggdp ~ risk,.) |>  summary()

# Estimate 12.87 risk = b0 + b1 logmortality
reg2 = ajr_df %>% lm(risk ~ logmort0,.) 
# Get the fitted values
risk_fitted = reg2$fitted.values
reg2 = summary(reg2)

# Estimate 12.88 logGdp = b0 + risk with risk now endogenous
reg3 = lm(ajr_df$loggdp ~ risk_fitted) |>  summary()

```

### Part b)

```{r include=FALSE}
# Restimate the above with both homoskedastic and heteroskedastic standard errors. The fixest package allows me to do this automatically
reg1_het = ajr_df %>% feols(loggdp ~ risk,., vcov = "HC1")
reg2_het = ajr_df %>% feols(risk ~ logmort0,., vcov = "HC1")
reg3_het = ajr_df %>% feols(loggdp ~ 1 | risk ~ logmort0,., vcov = "HC1")

# Compare SE's for 12.86
reg1$coefficients[2,2]; reg1_het$se[2] # Homoskedastic se's are reported

# 12.87
reg2$coefficients[2,2]; reg2_het$se[2] # Homoskedastic se's are reported

# 12.88
reg3$coefficients[2,2]; reg3_het$se[2] # Homoskedastic se's are reported
```

### Part c) 

```{r include=FALSE}
# Estimate 2SLS with indirect least squares
# First estimate effect of instrument on outcome
reg4 = ajr_df %>% lm(loggdp ~ logmort0,.) |> summary()

# Then divide that effect by effect of instrument on endogenous variable found in reg2
reg4$coefficients[2,1] / reg2$coefficients[2,1] # The same as part b
```


### Part d)

```{r include=FALSE}
# Estimate 2SLS with two stage approach
reg_2sls = ivreg(loggdp ~ risk | logmort0, data = ajr_df)
coef(reg_2sls)[2] # Same as before
```

### Part e)

```{r include=FALSE} 
# Get error terms from 2SLS regression and add them to data set
uhat2 = residuals(reg_2sls)

ajr_df = mutate(ajr_df, uhat2 = uhat2)

# Run control variable approach
reg_control = ajr_df %>% lm(loggdp ~ risk + logmort0 + uhat2,.)
coef(reg_control)[2]  #Same as before
```

### Part f)

```{r include=FALSE}
# Add latitude and africa as regressors
(reg_africa = ajr_df %>% lm(loggdp ~ risk + latitude + africa,.))
 # Africa is significant at any alpha level, lattitude is only significant at the 10% level
```

### Part g)

```{r include=FALSE}
(reg_africa_2sls = ivreg(loggdp ~ risk + africa + latitude | logmort0 + africa + latitude, data = ajr_df))
# Africa and latitude are not longer significant
```

### Part h)

```{r include=FALSE}
# Add exponential of mortality to data
ajr_df = mutate(ajr_df, mortality0 = exp(logmort0))

# Run baseline regresssion with mortality
(reg_mortality = ivreg(loggdp ~ risk | mortality0, data = ajr_df))
```


### Part i)

```{r include=FALSE}
# Add square root to data set
ajr_df = mutate(ajr_df, mortsquare = logmort0^2)

(reg_square = ivreg(loggdp ~ risk | mortality0 + mortsquare, data = ajr_df))
 # The result is back to the same result as earlier for risk
```

### Part j)

```{r include=FALSE}
stock_yogo_test(X =~ 1, D =~ risk, Z =~ mortality0 + mortsquare, B = 0.1,size_bias = "size", data = ajr_df)
```


### Part k)

```{r include=FALSE}
summary(reg_square, vcov = sandwich, diagnostics = TRUE)
```


### Part j)

```{r include=FALSE}
# Create IVmodel object
ivmod = ivmodel(Y = as.numeric(ajr_df$loggdp), D = as.numeric(ajr_df$risk), Z = ajr_df[, c("mortality0", "mortsquare")])

liml = LIML(ivmod)

liml$point.est
```

```{r}
# Efficient Gmm
gmm_mod = gmm4(loggdp ~ risk, ~ mortality0 + mortsquare, type = 'twostep', vcov = 'MDS', initW = "tsls", data = ajr_df)

summary(gmm_mod)
```

See above for estimates, standard errors. 

The J statistic is 0.64

The GMM, and 2SLS are basically identical.












